[build]
  publish = "build"
  command = "npm run build"

# Redirect all requests to the Edge Function for dynamic ad previews
[[redirects]]
  from = "/ads/*"
  to = "/.netlify/functions/ad-meta"
  status = 200
