[build]
  publish = "build"
  command = "CI= npm run build"

[[edge_functions]]
  path = "/ads/*"
  function = "ad-preview"
  
[[redirects]]
  from = "/api/*"
  to = "http://clarky.eu-north-1.elasticbeanstalk.com/:splat"
  status = 200
  force = true