[build]
  publish = "build"
  command = "CI= npm run build"

# Redirect all requests to the Edge Function for dynamic ad previews
[[redirects]]
  from = "/ads/*"
  to = "/netlify/functions/ad-preview"
  status = 200
