[build]
  publish = "build"
  command = "CI= npm run build"

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  path = "/ads/*"
  function = "ad-preview"

[[redirects]]
  from = "/ads/*"
  to = "/.netlify/edge-functions/ad-preview"
  status = 200
  force = true
