[build]
  publish = "build"
  command = "CI= npm run build"

[functions]
  directory = "netlify/functions"

[edge_functions]
  directory = "netlify/edge-functions"

[[redirects]]
  from = "/ads/*"
  to = "/.netlify/edge-functions/ad-preview"
  status = 200
  force = true
