const vehicles = [
  {
    code: "FLT001",
    make: "Toyota",
    model: "8FGCU25",
    capacity: 5000,
    fuelType: "Propane",
    yearManufactured: 2018,
    mastType: "Triple Stage",
    forkLength: 42,
    tireType: "Pneumatic",
    features: ["Side-shift", "Operator presence detection system"],
    priceUSD: 15000,
  },
  {
    code: "FLT002",
    make: "Hyster",
    model: "H50FT",
    capacity: 5000,
    fuelType: "Diesel",
    yearManufactured: 2019,
    mastType: "Quad Mast",
    forkLength: 48,
    tireType: "Cushion",
    features: ["Integral sideshifter", "Fork positioner"],
    priceUSD: 18500,
  },
  {
    code: "FLT003",
    make: "Crown",
    model: "SC 5300 Series",
    capacity: 3000,
    fuelType: "Electric",
    yearManufactured: 2020,
    mastType: "Two-Stage Mast",
    forkLength: 36,
    tireType: "Solid Rubber",
    features: ["Stand-up rider", "Power steering"],
    priceUSD: 12000,
  },
  {
    code: "FLT004",
    make: "Caterpillar",
    model: "GP25N",
    capacity: 5000,
    fuelType: "Gasoline",
    yearManufactured: 2017,
    mastType: "Full-Free Lift",
    forkLength: 42,
    tireType: "Pneumatic",
    features: ["Two-speed transmission", "Operator cab"],
    priceUSD: 16000,
  },
  {
    code: "FLT005",
    make: "Komatsu",
    model: "FB18M-2R",
    capacity: 3500,
    fuelType: "Electric",
    yearManufactured: 2021,
    mastType: "Triplex Mast",
    forkLength: 42,
    tireType: "Solid Rubber",
    features: ["Compact design", "Multi-function display"],
    priceUSD: 14000,
  },
  {
    code: "FLT006",
    make: "Yale",
    model: "GLC050VX",
    capacity: 5000,
    fuelType: "Propane",
    yearManufactured: 2016,
    mastType: "Quad Mast",
    forkLength: 48,
    tireType: "Pneumatic",
    features: ["Integral sideshifter", "Adjustable steering column"],
    priceUSD: 17000,
  },
  {
    code: "FLT007",
    make: "Linde",
    model: "H25D",
    capacity: 2500,
    fuelType: "Diesel",
    yearManufactured: 2018,
    mastType: "Two-Stage Mast",
    forkLength: 36,
    tireType: "Solid Rubber",
    features: ["Dual drive control", "Automatic transmission"],
    priceUSD: 13500,
  },
  {
    code: "FLT008",
    make: "Mitsubishi",
    model: "FGC25N",
    capacity: 5000,
    fuelType: "LPG",
    yearManufactured: 2019,
    mastType: "Triple Stage",
    forkLength: 42,
    tireType: "Pneumatic",
    features: ["Fork tilt", "Electronic throttle control"],
    priceUSD: 16500,
  },
  {
    code: "FLT009",
    make: "Clark",
    model: "C25L",
    capacity: 2500,
    fuelType: "Electric",
    yearManufactured: 2020,
    mastType: "Full-Free Lift",
    forkLength: 36,
    tireType: "Cushion",
    features: ["Clear-view mast", "Regenerative braking"],
    priceUSD: 14500,
  },
  {
    code: "FLT010",
    make: "Doosan",
    model: "G25E-5",
    capacity: 5000,
    fuelType: "Gasoline",
    yearManufactured: 2017,
    mastType: "Quad Mast",
    forkLength: 48,
    tireType: "Pneumatic",
    features: ["Auto-tilt leveling", "Load backrest extension"],
    priceUSD: 17500,
  },
];
